# CONFIG_BT_LL_SW_LLCP_LEGACY=y

#CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
#CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
#CONFIG_BT_BUF_ACL_TX_COUNT=32
#CONFIG_BT_L2CAP_TX_BUF_COUNT=32

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60


# Tap vs Hold 판정 시간 (ms)
CONFIG_ZMK_HOLD_TAP_DELAY=200
CONFIG_ZMK_HOLD_TAP_DECISION_TIMEOUT=200

# 빠른 연타 시 ESC 우선
CONFIG_ZMK_HOLD_TAP_PREFERRED_FLAVOR=tap-preferred


# ==============================
# Pointing device – Scroll tuning
# ==============================

# 세로 / 가로 스크롤 감도
CONFIG_ZMK_POINTING_SCROLL_MULTIPLIER_Y=12
CONFIG_ZMK_POINTING_SCROLL_MULTIPLIER_X=6

# 스크롤 분해능 (보통 1 유지)
CONFIG_ZMK_POINTING_SCROLL_DIVISOR=1

# 스크롤 방향 (필요한 것만 사용)
CONFIG_ZMK_POINTING_SCROLL_INVERT_Y=y
# CONFIG_ZMK_POINTING_SCROLL_INVERT_X=y

# ==============================
# RGB (현재 비활성)
# ==============================

# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_LED_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
